var localization = {
  "header.label.home": "헹헹!",
  "header.label.exam_site": "홍홍!",
  "header.label.greets": "",
  "header.button.remain": "퀭퀭!",
  "header.button.logout": "변경되는가튕튕!",
  "header.alert.logout": "ログアウトしますか?",
  "dashboard.header1": "AI面接受検現況",
  "dashboard.th.exam_name": "選考名",
  "dashboard.th.status": "進行状況",
  "dashboard.th.period": "受検期間",
  "dashboard.th.examinee": "対象者",
  "dashboard.th.done": "完了",
  "dashboard.th.not_take_exam": "未受検",
  "dashboard.th.num_of_incomplete": "未完了",
  "dashboard.th.exceed": "完了率",
  "dashboard.th.count_reset": "アクセス数超過",
  "dashboard.button.reset": "リセット",
  "dashboard.button.setting": "設定",
  "dashboard.label.counting": "〇人",
  "dashboard.label.active": "進行中",
  "dashboard.label.closed": "終了",
  "dashboard.label.step1": "選考設定",
  "dashboard.label.step2": "受検者設定",
  "dashboard.label.step3": "質問設定",
  "dashboard.label.step4": "結果表設定",
  "dashboard.label.step5": "案内メール&SMS設定",
  "regist.step1.header1": "AI面接管理",
  "regist.step1.header2": "登録",
  "regist.step1.basic.header": "基本設定",
  "regist.step1.basic.th.exam_name": "選考名",
  "regist.step1.basic.th.examinee": "受検者",
  "regist.step1.basic.label.at": "応募者",
  "regist.step1.basic.lable.mt": "在職者",
  "regist.step1.basic.th.examinee_detail": "受検者の詳細",
  "regist.step1.basic.label.new": "新卒",
  "regist.step1.basic.label.career": "中途",
  "regist.step1.basic.th.date": "受検期間",
  "regist.step1.basic.label.time": "時",
  "regist.step1.basic.guide": "※ 受検終了日から14日後にポイント精算が行われ、受検期間及び受検者の変更ができなくなります。",
  "regist.step1.basic.th.url": "홍홍!",
  "regist.step1.ai.header": "AI面接官設定",
  "regist.step1.ai.th.call_tts": "音声のテスト",
  "regist.step1.ai.button.call_tts": "音声を再生",
  "regist.step1.ai.guide": "テストするテキストを入力して事前に音声を確認してください。",
  "regist.step1.ai.line": "こんにちは、はじめまして。これからオンライン面接を開始します。",
  "regist.step1.ai.th.closing_remarks": "終わりの言葉",
  "regist.step1.ai.guide.closing_remarks": "受検終了後、応募者に案内される終わりの言葉を設定してください。",
  "regist.step1.ai.button.closing_remarks": "定番の言葉を適用",
  "regist.step1.ai.guide.closing_remarks2": "終わりの言葉は3個まで登録できます。",
  "regist.step1.ai.line.closing_remarks": "これでオンライン面接は全て終了しました。",
  "regist.step1.ai.line.closing_remarks2": "長い時間割いていただき、誠にありがとうございます。良い結果があることを願います。",
  "regist.step1.ai.th.external_link": "外部リンク設定",
  "regist.step1.ai.guide.external_link": "※受検終了後、外部サイトへの接続が必要な場合",
  "regist.step1.ai.guide.external_link2": "リンクテキスト入力",
  "regist.step1.ai.guide.external_link3": "URL入力",
  "regist.step1.result.header": "カスタマイズ設定",
  "regist.step1.result.th.customizing": "カスタマイズ",
  "regist.step1.result.label.none": "適用しない",
  "regist.step1.result.label.all": "一括適用",
  "regist.step1.result.label.all_null": "選択しない",
  "regist.step1.result.label.job_group": "職群別適用",
  "regist.step1.result.job_group_null": "選択しない",
  "regist.step1.result.th.display_yn": "結果表の表示設定",
  "regist.step1.result.guide.display_yn": "結果表でカスタマイズ設定を表示",
  "regist.step1.button.next": "次へ",
  "regist.step1.alert.save": "設定を保存しますか?",
  "regist.step1.label.confirm": "確認",
  "regist.step1.label.cancel": "キャンセル",
  "regist.step1.modal_blind.header": "結果表ブラインド設定",
  "regist.step1.modal_blind.guide": "ブラインドしようとする項目をOFF処理すると、ブラインドが適用されます。",
  "regist.step1.modal_jobfitness.header": "職務適合度表示設定",
  "regist.step1.modal_jobfitness.guide": "職群／職務適合度結果に表示される職務を選択してください。（職群別最大４つまで選択可能）",
  "regist.step1.modal_renamefacts.header": "力量名変更細部設定",
  "regist.step1.modal_renamefacts.guide": "以下の力量名と定義を確認し、変更しようとする力量名は右の空欄に作成してください。(12 byte 以内)",
  "regist.step1.modal_renamefacts.guide2": "変更したくない力量は空欄で結構です。",
  "regist.step2.header": "AI面接管理",
  "regist.step2.header2": "登録",
  "regist.step2.guide.fail_load": "情報の読み込みに失敗しました。もう一度やり直してください。",
  "regist.step2.label": "オンラインAI面接の登録可能",
  "regist.step2.label2": "人",
  "regist.step2.button.delete": "受検者削除",
  "regist.step2.alert.delete": "削除する受検者を選択してください。",
  "regist.step2.alert.delete2": "選択した受検者を削除しますか?",
  "regist.step2.alert.delete3": "受検を開始した対象者は削除できません。",
  "regist.step2.alert.delete4": "受検を開始している〇人の受検者を除き、残りの受検者を削除しますか?",
  "regist.step2.alert.delete5": "受検者削除に失敗しました。もう一度やり直してください。",
  "regist.step2.alert.delete6": "選択した受検者が削除されました。",
  "regist.step2.button.add": "受検者登録",
  "regist.step2.alert.add1": "保有ポイントが不足しています。受検者を追加するためには、ポイントを購入してください。",
  "regist.step2.label3": "総",
  "regist.step2.label4": "人",
  "regist.step2.button.download": "フォームをダウンロード",
  "regist.step2.alert.download": "フォームのダウンロードが完了しました。",
  "regist.step2.alert.download2": "フォームのダウンロードに失敗しました。もう一度やり直してください。",
  "regist.step2.button.upload": "Excelをアップロード",
  "regist.step2.alert.upload": "保有ポイントが不足しています。受検者を追加するためには、ポイントを購入してください。",
  "regist.step2.alert.upload2": "Excel統合ドキュメント(*.xlsx)ファイルを選択してください。",
  "regist.step2.alert.upload3": "選択したExcelファイルをアップロードしますか?",
  "regist.step2.alert.upload4": "ファイルが正常にアップロードされました。",
  "regist.step2.alert.upload5": "ファイルのアップロードに失敗しました。",
  "regist.step2.alert.upload6":
   "ファイルのアップロードに失敗した受検者がいます。失敗した受検者のリストを確認し、データを修正してもう一度やり直してください。",
  "regist.step2.alert.upload7": "ファイルのアップロードに失敗しました。正しくない形式のデータを修正してもう一度やり直してください。",
  "regist.step2.th.code": "受検番号/認証コード",
  "regist.step2.th.name": "名前",
  "regist.step2.th.job_group": "職群",
  "regist.step2.th.job_code": "職務",
  "regist.step2.th.sector": "所属部署/応募分野",
  "regist.step2.th.position": "職級",
  "regist.step2.th.gender": "性別",
  "regist.step2.th.birthday": "生年月日",
  "regist.step2.th.email": "メールアドレス",
  "regist.step2.th.phone": "携帯電話番号",
  "regist.step2.th.modify": "情報修正",
  "regist.step2.button.modify": "修正",
  "regist.step2.modal_add.header": "受検者情報登録",
  "regist.step2.modal_modify.header": "受検者情報修正",
  "regist.step2.modal_modify.name": "名前",
  "regist.step2.modal_modify.job_group": "職群を選択してください。",
  "regist.step2.modal_modify.job_code": "職務を選択してください。",
  "regist.step2.modal_modify.sector": "所属部署/応募分野",
  "regist.step2.modal_modify.email": "メール(例:user@email.com)チェック受検案内メールを発送可能",
  "regist.step2.modal_modify.male": "男",
  "regist.step2.modal_modify.female": "女",
  "regist.step2.modal_modify.birthday": "生年月日(例:19860312)",
  "regist.step2.modal_modify.phone": "携帯電話番号(例:090-1234-5678)※検査受検案内SMS発送可能",
  "regist.step2.modal_modify.position": "職級",
  "regist.step2.modal_modify.code": "受検番号 ※ 空欄の場合は自動生成",
  "regist.step2.modal_modify.button.save": "保存",
  "regist.step2.modal_modify.button.cancel": "キャンセル",
  "regist.step2.modal_modify.alert.name": "名前を入力してください。",
  "regist.step2.modal_modify.alert.job_group": "職群を選択してください。",
  "regist.step2.modal_modify.alert.job_code": "職務を選択してください。",
  "regist.step2.modal_modify.alert.sector": "所属部署/応募分野を入力してください。",
  "regist.step2.modal_modify.alert.email": "メールアドレスを入力してください。",
  "regist.step2.modal_modify.alert.email2": "メールアドレスを正しく入力してください。",
  "regist.step2.modal_modify.alert.phone": "携帯電話番号を入力してください。",
  "regist.step2.modal_modify.alert.birthday": "生年月日をYYYYMMDDのように入力してください。",
  "regist.step2.modal_modify.alert.birthday2": "生年月日を1月から12月の間に入力してください。",
  "regist.step2.modal_modify.alert.birthday3": "生年月日を1日から31日の間に入力してください。",
  "regist.step2.modal_modify.alert.phone2": "携帯電話番号は090-1234-5678のように入力してください。",
  "regist.step2.modal_modify.alert.fail": "受検者の修正に失敗しました。もう一度試してみてください。",
  "regist.step2.modal_add.alert.fail": "受検者の登録に失敗しました。もう一度試してみてください。",
  "regist.step2.modal_modify.alert.save": "保存しますか?",
  "regist.step2.modal_modify.alert.success": "修正されました。",
  "regist.step2.alert.empty": "登録された受検者がいません。",
  "regist.step3.header": "AI面接管理",
  "regist.step3.header2": "登録",
  "regist.step3.guide1": "基本質問、状況対処、深層会話、カスタム質問の構成を確認できます。",
  "regist.step3.guide2": "カスタム質問の設定から必要な質問を追加することができます。",
  "regist.step3.guide3": "以前の選考で使用した質問設定を読み込んで使用できます。",
  "result" : {
      "modal_email" : {
          "label" : "email1",
          "button" : "send1"
      },
      "modal_email_pretest" :{
          "label" : "email2",
          "button" : "쾡쿙!"
      }
  },
    "modal" : {
          "label" : "에취!",
          "button" : "send3"
    },
    "modal.label.button" : "send4"
};

define([], function(){
  return localization;
});
